### ISSUE TITLE
Weird bug - Might be C# error

### ISSUE THREAD

**Issue by iwilcove** [iwilcove/Dungeon-Game#2]
### **This bug can be found in the menu branch**

In GameFlowManager, adding this statement to Update()
`if (builtGrid = false)`
allows the game to function semi-properly.. Without it, it doesn't.

Here's the whole method:

```
    void Update () {
        //when this is added it works, but when it's gone it doesn't -- C# why u do this.
        if (builtGrid = false)
            //Debug.Log (builtGrid);

        // Check for next scene indicator
        if (Input.GetKeyDown ("t")) {
            dungeonPlayerScene ();
        }

        if (Application.loadedLevel == 1 && !builtGrid) {
            builtGrid = true;
            GameObject go = GameObject.Find("GridManager");
            GridCreator gc = (GridCreator) go.GetComponent(typeof(GridCreator));
            gc.BuildGrid ();
            Debug.Log (builtGrid);
        }

        if (Application.loadedLevel == 2 && !builtGrid) {
            builtGrid = true;
            GameObject go = GameObject.Find("GridManager");
            GridCreator gc = (GridCreator) go.GetComponent(typeof(GridCreator));
            gc.BuildGrid ();
            Debug.Log (builtGrid);
        }

    }
```

But this is not the C# error. The method would work fine if the `if` statements were working properly. The `if` statements ignore builtGrid, and wether it's true or not they still run. Those `Debug.Log (builtGrid);` statements show true, but if you put something in the `if` statement above then whatever is in it runs. This might be a C# bug, a unity bug, or a flaw in my logic that I don't see. I looked around on Unity Answers but everything on malfunctioning `if` statements are not related to the problem here.

So far this is the weirdest bug yet.

**Comment by yegorpetrov** [comment]
That's because `builtGrid = false` is an assignment, not a comparison. It makes your `builtGrid` false every time but still works as a [false] boolean expression for the `if`. I believe you wanted `if (builtGrid == false)` there.

Having `false` and `true` literals in conditions is asking for silly troubles like that. Either use variables as is (`if (flag) ...`) or invert with `!` as you did below.
